# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OTPLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OTPLogin
	pod 'Firebase/Core'
	pod 'Firebase/Auth'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
